<a href="https://colab.research.google.com/github/002Alok/movie-recommanded-system/blob/main/Train_model_on_ResNet50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install kaggle


In [1]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [3]:
!kaggle competitions download -c cifar-10

100% 714M/715M [00:24<00:00, 29.6MB/s]
100% 715M/715M [00:24<00:00, 31.0MB/s]


In [4]:
!ls


cifar-10.zip  kaggle.json  sample_data


In [5]:
from zipfile import ZipFile
file_name = "cifar-10.zip"

with ZipFile(file_name, 'r') as zip:
  zip.extractall()
  print('Done')

Done


In [6]:
!ls


cifar-10.zip  kaggle.json  sample_data	sampleSubmission.csv  test.7z  train.7z  trainLabels.csv


In [7]:
!pip install py7zr

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.9/67.9 kB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 23.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.2/96.2 kB 12.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.6/50.6 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 92.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.3/141.3 kB 17.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 413.7/413.7 kB 40.7 MB/s eta 0:00:00


In [9]:
import py7zr

archive=py7zr.SevenZipFile('train.7z', mode='r')
archive.extractall()
archive.close()
print('Done')

Done


In [10]:
import os
import numpy as np
import pandas as pd
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from sklearn.model_selection import train_test_split

In [11]:
filename=os.listdir('train')

In [12]:
type(filename)

list

In [13]:
len(filename)

50000

In [14]:
print(filename[0])

7251.png


In [16]:
lables_df = pd.read_csv('/content/trainLabels.csv')

In [17]:
lables_df.shape


(50000, 2)

In [18]:
lables_df.head()

,id,label
0,1,frog
1,2,truck
2,3,truck
3,4,deer
4,5,automobile


In [19]:
lables_df.tail()


,id,label
49995,49996,bird
49996,49997,frog
49997,49998,truck
49998,49999,automobile
49999,50000,automobile


In [21]:
lables_df[lables_df['id']==7251]

,id,label
7250,7251,frog


In [22]:
lables_df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [23]:
lables_df['label'].unique()

array(['frog', 'truck', 'deer', 'automobile', 'bird', 'horse', 'ship',
       'cat', 'dog', 'airplane'], dtype=object)

In [27]:
lables_df.count()

,0
id,50000
label,50000


In [28]:
lables_df['label'].value_counts()

,count
label,
frog,5000
truck,5000
deer,5000
automobile,5000
bird,5000
horse,5000
ship,5000
cat,5000
dog,5000


In [29]:
lables_dict={'airplane':0,'automobile':1,'bird':2,'cat':3,'deer':4,'dog':5,'frog':6,'horse':7,'ship':8,'truck':9}

In [30]:
lables_df['label'].apply(lambda x: lables_dict[x])

,label
0,6
1,9
2,9
3,4
4,1
...,...
49995,2
49996,6
49997,9
49998,1


In [32]:
label=lables_df['label'].apply(lambda x : lables_dict[x])


In [33]:
print(label)

0        6
1        9
2        9
3        4
4        1
        ..
49995    2
49996    6
49997    9
49998    1
49999    1
Name: label, Length: 50000, dtype: int64


In [34]:
train_data_folder='/content/train/'
data=[]
id_list = lables_df['id']
for id in id_list:
  image = Image.open(train_data_folder+str(id)+'.png')
  image=np.array(image)
  data.append(image)

In [36]:
type(data)

list

In [37]:
len(data)

50000

In [38]:
type(data[0])

numpy.ndarray

In [39]:
data[0].shape

(32, 32, 3)

In [61]:
x = np.array(data)
y = np.array(label)

In [53]:
print(x.shape)
print(y.shape)

(50000, 32, 32, 3)
(50000,)


In [54]:
print(data[0])

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [55]:
print(x[0])

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [62]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [63]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(40000, 32, 32, 3)
(10000, 32, 32, 3)
(40000,)
(10000,)


In [64]:
print(x_train[0])

[[[34 36 43]
  [37 37 51]
  [44 44 64]
  ...
  [62 73 93]
  [52 63 83]
  [45 57 77]]

 [[35 35 37]
  [34 34 40]
  [34 33 43]
  ...
  [58 69 89]
  [50 60 80]
  [47 58 78]]

 [[34 33 35]
  [33 32 36]
  [33 32 38]
  ...
  [66 77 97]
  [51 62 82]
  [53 64 84]]

 ...

 [[32 32 38]
  [32 31 37]
  [33 33 38]
  ...
  [41 38 45]
  [34 31 38]
  [36 32 40]]

 [[33 31 36]
  [32 30 36]
  [34 32 37]
  ...
  [37 35 40]
  [32 29 35]
  [30 28 33]]

 [[37 32 35]
  [37 32 36]
  [37 33 36]
  ...
  [49 47 49]
  [47 45 48]
  [58 56 58]]]


In [65]:
x_test_scaled=x_test/255
x_train_scaled=x_train/255

In [ ]:
_

Build Neural Network


In [66]:
import tensorflow as tf
from tensorflow import keras

In [72]:
from keras.models import Sequential
from keras.layers import Dense,Flatten,Conv2D,MaxPooling2D

In [73]:
no_of_classes=10

model = Sequential()
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(32,32,3)))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(no_of_classes,activation='softmax'))

In [74]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [76]:
model.fit(x_train_scaled,y_train,validation_split=0.1,epochs=20)

Epoch 1/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8793 - loss: 0.3429 - val_accuracy: 0.6625 - val_loss: 1.3121
Epoch 2/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.8930 - loss: 0.3015 - val_accuracy: 0.6607 - val_loss: 1.3936
Epoch 3/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9024 - loss: 0.2865 - val_accuracy: 0.6562 - val_loss: 1.4891
Epoch 4/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - accuracy: 0.9113 - loss: 0.2513 - val_accuracy: 0.6653 - val_loss: 1.5338
Epoch 5/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.9208 - loss: 0.2280 - val_accuracy: 0.6528 - val_loss: 1.6623
Epoch 6/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9258 - loss: 0.2096 - val_accuracy: 0.6510 - val_loss: 1.6878
Epoch 7/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9320 - loss: 0.1923 - val_accuracy: 0.6522 - val_loss: 1.8222
Epoch 8/20
1125/1125 ━━━━━━━━━━━━━━━━━━━━ 5s 4ms/step - accuracy: 0.9363 - loss: 0.1779 - 

In [83]:
y_pred=model.predict(x_test_scaled)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [81]:
model.predict(x_test_scaled)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


array([[6.8532825e-07, 1.9254435e-11, 8.6971121e-03, ..., 1.1931206e-03,
        8.7103331e-11, 1.8170365e-08],
       [3.7841435e-11, 4.9537514e-18, 1.1097444e-14, ..., 5.4814704e-15,
        9.9999940e-01, 5.3935361e-07],
       [9.9931407e-01, 1.7156552e-08, 2.7169881e-05, ..., 8.9537550e-10,
        6.1436411e-04, 8.8651523e-06],
       ...,
       [2.7470132e-13, 1.1198108e-14, 7.8596022e-17, ..., 2.3145796e-18,
        1.0000000e+00, 9.2186810e-14],
       [2.5181691e-19, 7.9280531e-15, 6.9048045e-05, ..., 4.5950951e-08,
        3.4467832e-23, 3.4175858e-16],
       [1.1996638e-04, 5.1632037e-07, 4.5257502e-07, ..., 1.4499335e-09,
        5.8523035e-08, 2.5099324e-04]], dtype=float32)

In [84]:
from sklearn.metrics import confusion_matrix

In [86]:
from keras.layers import BatchNormalization
from keras.models import load_model,Model
from keras.applications.resnet50 import ResNet50
from keras import optimizers

In [ ]:
conv_base=ResNet50(weights='imagenet',include_top=False,input_shape=(256,256,3))